name: tests
on:
  push:
    branches:
    - 'main'
  pull_request:
jobs:
  build:
    name: run basic test
    runs-on: "ubuntu-latest"
    env:
      TEST_VAR: ${{ secrets.TEST_VAR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - run: pip install nox

      - name: Run nox session
        run: nox --sessions test-3.9
